//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADTool ähnelt.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blank ähnelt.
        /// </summary>
        public static string BlankPageTitle {
            get {
                return ResourceManager.GetString("BlankPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check_User_Account ähnelt.
        /// </summary>
        public static string Check_User_AccountPageTitle {
            get {
                return ResourceManager.GetString("Check_User_AccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create_User ähnelt.
        /// </summary>
        public static string Create_UserPageTitle {
            get {
                return ResourceManager.GetString("Create_UserPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete_Device ähnelt.
        /// </summary>
        public static string Delete_DevicePageTitle {
            get {
                return ResourceManager.GetString("Delete_DevicePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable_Enable_Account ähnelt.
        /// </summary>
        public static string Disable_Enable_AccountPageTitle {
            get {
                return ResourceManager.GetString("Disable_Enable_AccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable_Account ähnelt.
        /// </summary>
        public static string Enable_AccountPageTitle {
            get {
                return ResourceManager.GetString("Enable_AccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get_Bitlocker ähnelt.
        /// </summary>
        public static string Get_BitlockerPageTitle {
            get {
                return ResourceManager.GetString("Get_BitlockerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LAPS ähnelt.
        /// </summary>
        public static string LAPSPageTitle {
            get {
                return ResourceManager.GetString("LAPSPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample Orders ähnelt.
        /// </summary>
        public static string ListDetailsListDescription {
            get {
                return ResourceManager.GetString("ListDetailsListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ListDetails ähnelt.
        /// </summary>
        public static string ListDetailsPageTitle {
            get {
                return ResourceManager.GetString("ListDetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click to log in ähnelt.
        /// </summary>
        public static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log In ähnelt.
        /// </summary>
        public static string LogInPageTitle {
            get {
                return ResourceManager.GetString("LogInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset_User_Password ähnelt.
        /// </summary>
        public static string Reset_User_PasswordPageTitle {
            get {
                return ResourceManager.GetString("Reset_User_PasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings page placeholder text.  Your app description goes here. ähnelt.
        /// </summary>
        public static string SettingsPageAboutText {
            get {
                return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About this application ähnelt.
        /// </summary>
        public static string SettingsPageAboutTitle {
            get {
                return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose Theme ähnelt.
        /// </summary>
        public static string SettingsPageChooseThemeText {
            get {
                return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out ähnelt.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personalization ähnelt.
        /// </summary>
        public static string SettingsPagePersonalizationTitle {
            get {
                return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy Statement ähnelt.
        /// </summary>
        public static string SettingsPagePrivacyStatementText {
            get {
                return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonDarkTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonLightTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string SettingsPageRadioButtonWindowsDefaultTheme {
            get {
                return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blank ähnelt.
        /// </summary>
        public static string ShellBlankPage {
            get {
                return ResourceManager.GetString("ShellBlankPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check_User_Account ähnelt.
        /// </summary>
        public static string ShellCheck_User_AccountPage {
            get {
                return ResourceManager.GetString("ShellCheck_User_AccountPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create_User ähnelt.
        /// </summary>
        public static string ShellCreate_UserPage {
            get {
                return ResourceManager.GetString("ShellCreate_UserPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete_Device ähnelt.
        /// </summary>
        public static string ShellDelete_DevicePage {
            get {
                return ResourceManager.GetString("ShellDelete_DevicePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable_Enable_Account ähnelt.
        /// </summary>
        public static string ShellDisable_Enable_AccountPage {
            get {
                return ResourceManager.GetString("ShellDisable_Enable_AccountPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable_Account ähnelt.
        /// </summary>
        public static string ShellEnable_AccountPage {
            get {
                return ResourceManager.GetString("ShellEnable_AccountPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get_Bitlocker ähnelt.
        /// </summary>
        public static string ShellGet_BitlockerPage {
            get {
                return ResourceManager.GetString("ShellGet_BitlockerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Go back ähnelt.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open or close navigation ähnelt.
        /// </summary>
        public static string ShellHamburgerButtonName {
            get {
                return ResourceManager.GetString("ShellHamburgerButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LAPS ähnelt.
        /// </summary>
        public static string ShellLAPSPage {
            get {
                return ResourceManager.GetString("ShellLAPSPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ListDetails ähnelt.
        /// </summary>
        public static string ShellListDetailsPage {
            get {
                return ResourceManager.GetString("ShellListDetailsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset_User_Password ähnelt.
        /// </summary>
        public static string ShellReset_User_PasswordPage {
            get {
                return ResourceManager.GetString("ShellReset_User_PasswordPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string ShellSettingsPage {
            get {
                return ResourceManager.GetString("ShellSettingsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something went wrong during the login, please try again. ähnelt.
        /// </summary>
        public static string StatusLoginFails {
            get {
                return ResourceManager.GetString("StatusLoginFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no internet connection, please connect to the internet and try again. ähnelt.
        /// </summary>
        public static string StatusNoNetworkAvailable {
            get {
                return ResourceManager.GetString("StatusNoNetworkAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User is unauthorized ähnelt.
        /// </summary>
        public static string StatusUnauthorized {
            get {
                return ResourceManager.GetString("StatusUnauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add_Remove_User_Group.
        /// </summary>
        public static string Add_Remove_User_GroupPageTitle
        {
            get
            {
                return ResourceManager.GetString("Add_Remove_User_GroupPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add_Remove_User_Group.
        /// </summary>
        public static string ShellAdd_Remove_User_GroupPage
        {
            get
            {
                return ResourceManager.GetString("ShellAdd_Remove_User_GroupPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersPageTitle
        {
            get
            {
                return ResourceManager.GetString("UsersPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string ShellUsersPage
        {
            get
            {
                return ResourceManager.GetString("ShellUsersPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardPageTitle
        {
            get
            {
                return ResourceManager.GetString("DashboardPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string ShellDashboardPage
        {
            get
            {
                return ResourceManager.GetString("ShellDashboardPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrebuildComputers.
        /// </summary>
        public static string PrebuildComputersPageTitle
        {
            get
            {
                return ResourceManager.GetString("PrebuildComputersPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PrebuildComputers.
        /// </summary>
        public static string ShellPrebuildComputersPage
        {
            get
            {
                return ResourceManager.GetString("ShellPrebuildComputersPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NewUser.
        /// </summary>
        public static string NewUserPageTitle
        {
            get
            {
                return ResourceManager.GetString("NewUserPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NewUser.
        /// </summary>
        public static string ShellNewUserPage
        {
            get
            {
                return ResourceManager.GetString("ShellNewUserPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable_Device.
        /// </summary>
        public static string Enable_DevicePageTitle
        {
            get
            {
                return ResourceManager.GetString("Enable_DevicePageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable_Device.
        /// </summary>
        public static string ShellEnable_DevicePage
        {
            get
            {
                return ResourceManager.GetString("ShellEnable_DevicePage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add_SharedMailboxUser.
        /// </summary>
        public static string Add_SharedMailboxUserPageTitle
        {
            get
            {
                return ResourceManager.GetString("Add_SharedMailboxUserPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add_SharedMailboxUser.
        /// </summary>
        public static string ShellAdd_SharedMailboxUserPage
        {
            get
            {
                return ResourceManager.GetString("ShellAdd_SharedMailboxUserPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OneDriveProvisioning.
        /// </summary>
        public static string OneDriveProvisioningPageTitle
        {
            get
            {
                return ResourceManager.GetString("OneDriveProvisioningPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OneDriveProvisioning.
        /// </summary>
        public static string ShellOneDriveProvisioningPage
        {
            get
            {
                return ResourceManager.GetString("ShellOneDriveProvisioningPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create_Shared_Mailbox.
        /// </summary>
        public static string Create_Shared_MailboxPageTitle
        {
            get
            {
                return ResourceManager.GetString("Create_Shared_MailboxPageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create_Shared_Mailbox.
        /// </summary>
        public static string ShellCreate_Shared_MailboxPage
        {
            get
            {
                return ResourceManager.GetString("ShellCreate_Shared_MailboxPage", resourceCulture);
            }
        }
    }
}
